// ============================================
// Initial Seed Data for Ocean MGPS Database
// ============================================

export const INITIAL_PRODUCTS = [
  {
    name: "12-Channel ECG Machine",
    category: "ICU & Diagnostic Equipment",
    description: "High-precision 12-channel electrocardiograph with 7-inch color display, built-in thermal printer, auto-analysis, and arrhythmia detection.",
    specifications: "Sampling rate: 1000Hz, Paper size: 210mmx140mm, Battery backup: 4+ hours, Storage: 500+ ECG records.",
    images: ["/images/products/gas-alarm-system.png"],
    featured: true,
    status: "published",
    order: 1,
  },
  {
    name: "Multi-Para Patient Monitor",
    category: "ICU & Diagnostic Equipment",
    description: "Multi-parameter patient monitor tracking ECG, NIBP, SpO2, Resp, Temp, and dual IBP for intensive care units and operating rooms.",
    specifications: "12.1-inch TFT touch screen, 168-hour trend data review, ST segment & arrhythmia analysis, Li-ion rechargeable battery.",
    images: ["/images/products/gas-alarm-system.png"],
    featured: true,
    status: "published",
    order: 2,
  },
  {
    name: "Volumetric Infusion Pump",
    category: "ICU & Diagnostic Equipment",
    description: "Microprocessor-controlled volumetric infusion pump with peristaltic mechanism, anti-bolus system, and multi-channel safety alarms.",
    specifications: "Flow rate: 0.1 - 1200 ml/h, Accuracy: ±5%, Occlusion detection: 3 pressure levels, Battery: 6 hours.",
    images: ["/images/products/vacuum-regulator.png"],
    featured: true,
    status: "published",
    order: 3,
  },
  {
    name: "Micro Syringe Pump",
    category: "ICU & Diagnostic Equipment",
    description: "High-accuracy micro syringe driver supporting 10ml, 20ml, 30ml, and 50/60ml syringes for critical drug delivery in NICU & ICU.",
    specifications: "Infusion rate: 0.1 - 1500 ml/h, Syringe auto-recognition, KVO rate: 0.1 - 5 ml/h, Visual & audible alarm system.",
    images: ["/images/products/vacuum-regulator.png"],
    featured: true,
    status: "published",
    order: 4,
  },
  {
    name: "Advanced ICU Ventilator",
    category: "ICU & Diagnostic Equipment",
    description: "Comprehensive invasive and non-invasive ICU ventilator suitable for neonatal, pediatric, and adult patients.",
    specifications: "Tidal Volume: 20-2000ml, Modes: VCV, PCV, SIMV, PSV, CPAP/BiPAP, Integrated turbine drive with O2 mixer.",
    images: ["/images/products/oxygen-flow-meter.png"],
    featured: true,
    status: "published",
    order: 5,
  },
  {
    name: "Infant Radiant Warmer",
    category: "ICU & Diagnostic Equipment",
    description: "Microprocessor temperature-controlled infant radiant warmer with skin/manual modes, LED examination lamp, and ceramic heater element.",
    specifications: "Temperature range: 30°C - 38°C, Accuracy: ±0.1°C, Safety cut-off at 39°C, Integrated APGAR timer.",
    images: ["/images/products/bed-head-panel.png"],
    featured: true,
    status: "published",
    order: 6,
  },
  {
    name: "Oxygen BPC Flow Meter",
    category: "Flow Meters & Regulators",
    description: "Hospital-grade Oxygen BPC Flow Meter with unbreakable polycarbonate humidifier bottle and nickel-plated brass body.",
    specifications: "Flow rate: 0-15 L/min, Calibrated at 60 PSI, Inlet connection: Probe type / Threaded, Safety relief valve included.",
    images: ["/images/products/oxygen-flow-meter.png"],
    featured: true,
    status: "published",
    order: 7,
  },
  {
    name: "Medical Gas Outlet Point",
    category: "Medical Gas Outlets",
    description: "BS/DIN standard quick-connect gas outlets for Oxygen, Nitrous Oxide, Compressed Air, CO2, and Vacuum with double sealing valves.",
    specifications: "Color-coded as per ISO 9170-1, Gas-specific non-interchangeable probe indexing, 360-degree swivel inlet pipe.",
    images: ["/images/products/medical-gas-outlet.png"],
    featured: true,
    status: "published",
    order: 8,
  },
  {
    name: "Medical Gas Manifold System",
    category: "Manifold Systems",
    description: "Automatic changeover cylinder manifold system available in 2x2, 4x4, 6x6, and 10x10 configurations for uninterrupted gas delivery.",
    specifications: "Automatic pneumatic changeover, Pressure regulators with dual gauges, High-pressure copper pigtails with non-return valves.",
    images: ["/images/products/manifold-system.png"],
    featured: true,
    status: "published",
    order: 9,
  },
  {
    name: "Medical Copper Fittings & Pipes",
    category: "Copper Fittings & Pipes",
    description: "Deoxidized high-phosphorus seamless copper pipes (BS EN 13348 / IS 191 standard) for medical gas and LPG laboratory piping.",
    specifications: "Purity: 99.9% Cu, Outer diameter: 10mm to 108mm, Degreased & capped ends, Pressure tested to 35 bar.",
    images: ["/images/products/copper-pipe-fittings.png"],
    featured: true,
    status: "published",
    order: 10,
  },
  {
    name: "Bed Head Panel Unit",
    category: "Bed Head Panels",
    description: "Extruded aluminum powder-coated bed head panel with segregated compartments for medical gases, electrical sockets, and nurse call.",
    specifications: "Customizable length (1.2m to 2.4m), 4-6 gas outlets, 6-8 electrical sockets (6A/16A), Reading light & RJ45 data port.",
    images: ["/images/products/bed-head-panel.png"],
    featured: true,
    status: "published",
    order: 11,
  },
  {
    name: "Modular Operation Theater & Pendant",
    category: "OT Equipment",
    description: "Turnkey Modular OT setup with stainless steel / GI wall paneling, laminar airflow ceiling, ceiling-mounted motorized OT pendant & LED lights.",
    specifications: "NABH compliant, Hermetically ceiling-sealed doors, Anti-static conductive flooring, Control panel with digital clock & pressure display.",
    images: ["/images/products/modular-ot.png"],
    featured: true,
    status: "published",
    order: 12,
  },
  {
    name: "Anti-Microbial Hospital Cubicle Curtains",
    category: "OT Equipment",
    description: "Fire-retardant, stain-resistant, anti-bacterial cubicle curtain fabric with aluminum ceiling track rail systems for patient privacy.",
    specifications: "Fabric: 100% Polyester FR, Mesh top: 20-24 inch mesh, Ceiling track: Heavy-duty aluminum track with roller runners.",
    images: ["/images/products/bed-head-panel.png"],
    featured: true,
    status: "published",
    order: 13,
  },
  {
    name: "LPG Gas Copper Piping System for Labs",
    category: "LPG Gas Copper Systems",
    description: "High-safety LPG copper gas manifold & piping system designed for chemistry laboratories, research institutions, and industrial setups.",
    specifications: "Bunsen burner needle valve outlets, Master instructor cutoff valve, Gas leak detection alarm sensor, High-pressure regulators.",
    images: ["/images/products/copper-pipe-fittings.png"],
    featured: true,
    status: "published",
    order: 14,
  },
];

export const INITIAL_PROJECTS = [
  {
    title: "Turnkey MGPS & Modular OT Setup — Apex Multi-Specialty Hospital",
    client: "Apex Hospital (150 Beds)",
    location: "Chh. Sambhaji Nagar, Maharashtra",
    description: "Complete design, supply, installation, testing, and commissioning of Medical Gas Pipeline System (Oxygen, Vacuum, Air, CO2) with 4-chamber Automatic Cylinder Manifold, 2 Modular Operation Theaters, and 60 Bed Head Panels.",
    completionDate: "January 2025",
    images: ["/images/products/modular-ot.png", "/images/products/manifold-system.png"],
    videos: ["https://www.youtube.com/watch?v=k3_tw44QsZQ", "https://www.youtube.com/watch?v=21X5lGlDOfg"],
    category: "MGPS Installation",
    featured: true,
    status: "published",
  },
  {
    title: "Hospital Oxygen Manifold & Vacuum System Installation",
    client: "Lifeline Critical Care Hospital",
    location: "Jalna, Maharashtra",
    description: "Installation of 10x10 automatic oxygen manifold system, liquid oxygen booster pipeline network, digital zone valve alarm boxes, and ICU patient monitor brackets.",
    completionDate: "November 2024",
    images: ["/images/products/manifold-system.png", "/images/products/gas-alarm-system.png"],
    videos: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
    category: "MGPS Installation",
    featured: true,
    status: "published",
  },
  {
    title: "Commercial & Lab LPG Copper Gas Pipeline Setup",
    client: "Commercial Kitchens & Research Institute",
    location: "Chh. Sambhaji Nagar, Maharashtra",
    description: "Custom heavy-duty copper gas pipeline network with 4x4 cylinder manifold bank, Bunsen burner outlets, instructor safety shutoff, and automatic LPG leak detection alarms.",
    completionDate: "August 2024",
    images: ["/images/projects/lpg-manifold-installation.jpg", "/images/products/copper-pipe-fittings.png"],
    videos: ["https://www.youtube.com/watch?v=7wtfhZwyrcc"],
    category: "LPG Copper Pipeline",
    featured: true,
    status: "published",
  },
  {
    title: "Pediatric & NICU Medical Gas Pipeline Expansion",
    client: "Sunrise Children's Hospital",
    location: "Beed, Maharashtra",
    description: "Expansion of NICU gas supply lines with micro syringe pump mounts, infant radiant warmer gas hookups, BPC oxygen flow meters, and anti-microbial cubicle track curtains.",
    completionDate: "May 2024",
    images: ["/images/products/oxygen-flow-meter.png", "/images/products/vacuum-regulator.png"],
    videos: ["https://www.youtube.com/watch?v=kJQP7kiw5Fk"],
    category: "Hospital Setup",
    featured: true,
    status: "published",
  },
];

export const INITIAL_SERVICES = [
  {
    title: "MGPS Installation (Oxygen, Air, CO2, Nitrogen, Vacuum & Outlets)",
    category: "Installation",
    shortDescription: "Complete installation of centralized hospital gas supply pipelines, manifolds, alarm panels, and gas terminal outlets.",
    fullDescription: "We specialize in end-to-end turnkey installation of Medical Gas Pipeline Systems (MGPS) adhering to IS 7484 and HTM 02-01 standard guidelines. Our installation covers central oxygen manifolds, compressed air 4-bar and 7-bar systems, nitrous oxide lines, medical vacuum plants, digital alarm boxes, area valve service units (AVSU), and self-sealing outlet terminal points.",
    tagline: "End-to-end hospital gas pipeline engineering & IS 7484 certification",
    badge: "Full Turnkey",
    leadTime: "10-30 Days",
    icon: "Activity",
    features: [
      "Oxygen, Medical Air, CO2, Nitrogen, Vacuum & Outlet installation",
      "Automatic cylinder manifold changeover systems",
      "Digital pressure monitoring and safety alarm panels",
      "BS / DIN quick-connect medical gas outlet points",
      "Zone valve isolation units for safe ward maintenance",
    ],
    order: 1,
    status: "published",
  },
  {
    title: "LPG Copper Gas Pipeline for Hospitals & Chemistry Labs",
    category: "LPG Piping",
    shortDescription: "High-safety copper LPG gas piping for hospital canteens, science research laboratories, and educational institutions.",
    fullDescription: "Engineering-grade LPG gas copper piping systems designed for maximum safety in hospitals, chemistry laboratories, schools, colleges, and industrial setups. Equipped with Bunsen burner needle control valves, instructor master cutoff switches, high-pressure regulators, and electronic gas leak detection alarms.",
    tagline: "Centralized LPG copper gas piping for homes, hotels, restaurants & labs",
    badge: "IS 6044 / PESO Certified",
    leadTime: "3-10 Days",
    icon: "Flame",
    features: [
      "High-purity seamless copper piping for LPG delivery",
      "Bunsen burner needle control valves for science labs",
      "Instructor master emergency gas shutoff mechanism",
      "Gas leak detection alarm system & safety shut-off valves",
      "Commercial & institution LPG manifold setup",
    ],
    order: 2,
    status: "published",
  },
  {
    title: "Medical Equipment Sales & Hospital Device Supply",
    category: "Equipment",
    shortDescription: "We serve all types of hospital equipment — ICU diagnostic monitors, ECG machines, ventilators, pumps & warmers.",
    fullDescription: "Authorized stockist, supplier, and distributor of complete hospital medical equipment across India. We supply 12-channel ECG machines, multi-para monitors, volumetric infusion pumps, micro syringe pumps, advanced ventilators, infant radiant warmers, BPC flow meters, vacuum regulators, bed head panels, and anti-microbial cubicle curtains.",
    tagline: "Certified stockist & supplier of hospital gas hardware & ICU devices",
    badge: "Certified Hardware & ICU Devices",
    leadTime: "Immediate Stock / Fast Dispatch",
    icon: "Stethoscope",
    features: [
      "We serve all types of hospital equipment across India",
      "12-Channel ECG Machines & Multi-Para Patient Monitors",
      "Advanced ICU Ventilators, Infusion & Syringe Pumps",
      "Infant Radiant Warmers & Pediatric Care Equipment",
      "Anti-Microbial Hospital Cubicle Curtains & Ceiling Track Systems",
    ],
    order: 3,
    status: "published",
  },
  {
    title: "Modular Operation Theater (OT) & Pendant Setup",
    category: "Modular OT",
    shortDescription: "Turnkey Modular OT design, anti-static flooring, ceiling pendants, laminar airflow, and hermetic door setups.",
    fullDescription: "Complete engineering and execution of NABH-compliant Modular Operation Theaters. Includes stainless steel / GI wall paneling, HEPA filter laminar airflow ceilings, ceiling-suspended motorized pendants, surgical LED light tracks, anti-static conductive flooring, and integrated OT control panels.",
    tagline: "Sterile surgical environments with integrated gas supply & laminar flow",
    badge: "NABH Compliant",
    leadTime: "15-45 Days",
    icon: "Wrench",
    features: [
      "NABH-compliant modular OT wall and ceiling paneling",
      "Laminar airflow system with HEPA filtration",
      "Motorized single and dual arm ceiling pendants",
      "Anti-static epoxy conductive flooring",
      "Surgical LED OT lights and surgeon control panel",
    ],
    order: 4,
    status: "published",
  },
  {
    title: "MGPS Maintenance, Pipeline Testing & Safety Certification",
    category: "Maintenance",
    shortDescription: "Comprehensive repair, pressure testing, gas purity audit, and 1-year free service coverage.",
    fullDescription: "Professional maintenance, repair, and annual calibration for hospital gas pipeline networks, manifolds, vacuum pumps, and regulators. We perform 35-bar pressure leak tests, gas purity audits, and issue safety compliance certificates for NABH accreditation.",
    tagline: "24/7 emergency repair & annual maintenance for MGPS pipelines & ICU equipment",
    badge: "24/7 Emergency & ICU AMC",
    leadTime: "Instant Helpline / On-Site Dispatch",
    icon: "ShieldCheck",
    features: [
      "1-Year free service warranty on all our installations",
      "35-bar pressure leak testing & gas purity verification",
      "Emergency repair & 24/7 technical service support",
      "Manifold & regulator overhaul & replacement parts",
      "NABH compliance audit and safety certification",
    ],
    order: 5,
    status: "published",
  },
];
